default_stages:
  - commit
exclude: >
  (?x)^(
    ^(\/|)vendor\/(.*?)$|
    .+\.node_modules\/.*$|
    .+\.lock$|
  )$

repos:
  - repo: https://github.com/codespell-project/codespell
    rev: v2.1.0
    hooks:
      - id: codespell
        args: [--ignore-words=.codespell-ignores]
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v8.0.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ['@hadenlabs/commitlint-config']
        args:
          - --config=.ci/linters/.commitlintrc.json
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: detect-private-key
        files: ^(?!\.?git-crypt)
        exclude: >
          (?x)^(
            .+\.gitleaks.toml$|
          )$
      - id: check-merge-conflict
      - id: check-added-large-files
        files: ^tf|-|\.(py|env|yml|yaml)$
      - id: check-case-conflict
      - id: check-json
      - id: check-xml
      - id: check-yaml
        args:
          - --allow-multiple-documents
      - id: check-byte-order-marker
      - id: check-ast
      - id: debug-statements
      - id: check-docstring-first
      - id: requirements-txt-fixer
      - id: check-symlinks
      - id: file-contents-sorter
      - id: fix-encoding-pragma
      - id: sort-simple-yaml
  - repo: https://github.com/hadenlabs/pre-commit-hooks
    rev: 47e07f691058d12b2f8f49912b5568654d26331f
    hooks:
      - id: do-not-commit
      - id: markdown-link-check
        args:
          - --config=.ci/linters/markdown-link-config.json
        exclude: \.tpl.md$
      - id: shellcheck
        exclude: >
          (?x)^(
            .+\.provision/git/hooks/prepare-commit-msg$|
            .+\.tpl.sh$|
          )$
        args:
          - --exclude=SC1072,SC1073,SC2068
      - id: gitleaks
        args:
          - --path=.
          - --repo-config-path=.ci/linters/.gitleaks.toml
          - --verbose
      - id: hadolint
        args:
          - --config=.ci/linters/.hadolint.yaml
